# Generated by Django 6.0.1 on 2026-01-19 06:46

import apps.link_shortener.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_shortener', '0002_alter_shortlink_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortlink',
            options={'ordering': ['-created_at'], 'verbose_name': 'Short Link', 'verbose_name_plural': 'Short Links'},
        ),
        migrations.AddField(
            model_name='shortlink',
            name='clicks',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the link was clicked'),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the short link was created'),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the link expires (optional)', null=True),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the link is active'),
        ),
        migrations.AddField(
            model_name='shortlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the short link was last updated'),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='alias',
            field=models.CharField(default=apps.link_shortener.models.create_alias, help_text='Short alias for the URL', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='shortlink',
            name='url',
            field=models.URLField(help_text='The original URL to shorten', max_length=2048),
        ),
    ]
